/* ============================================================
   content-config.js — AUTO-GENERATED by sync-content.js
   Do not edit by hand: your changes will be overwritten.

   To add a study guide or mock test:
     1. Put the .html file in  library/  or  tests/
     2. Run:  node sync-content.js
     3. git add . && git commit -m "add file" && git push

   Generated: 2026-07-19
   ============================================================ */

window.LIBRARY_FILES = [
  {
    "name": "Data Engineering Bible 2026",
    "desc": "A-to-Z roadmap • ~850 interview Q&A • hands-on playbooks",
    "file": "DE_Bible_2026.html"
  },
  {
    "name": "DE Interview Crash Bible 2026",
    "desc": "Practical theory + high-signal interview Q&A, fused. Built to crack a Data Engineer role in <15 days.",
    "file": "DE_Interview_Crash_Bible_2026.html"
  },
  {
    "name": "Data Engineering Theory Bible 2026",
    "desc": "Complete theory of every DE topic • from zero to deep • real-project flowmaps",
    "file": "DE_Theory_Bible_2026.html"
  },
  {
    "name": "Enterprise Data Engineering Handbook 2026",
    "desc": "How real client DE projects are actually designed, built, shipped, run & discussed — written like internal project documentation.",
    "file": "Enterprise_DE_Handbook_2026.html"
  },
  {
    "name": "Mega-Scale DE Blueprints 2026",
    "desc": "Five FAANG-scale platforms as technical blueprints — the exact data flow, every transformation step, and what tech sits between each hop.",
    "file": "MegaScale_DE_Blueprints_2026.html"
  }
];

window.TEST_FILES = [
  {
    "name": "DE-100 | Deepesh's Data Engineering Mock Test",
    "desc": "Built for Deepesh — SQL, Python, Spark, Kafka, Airflow, Snowflake, Databricks, Azure, Warehousing & Data Quality. Every answer explains itself, right…",
    "file": "DE-100_Mock_Test.html"
  },
  {
    "name": "DE-101 | Advanced Data Engineering Mock Test - Vol 1",
    "desc": "The next step up from DE-100. More debugging, more code-output questions, more tuning scenarios, more edge cases. Written to press exactly the spots…",
    "file": "DE-101_Mock_Test.html"
  },
  {
    "name": "DE-102 | Advanced Data Engineering Mock Test - Vol 2",
    "desc": "The final tier. Real production scenarios, deep internals, architectural tradeoffs, on-call debugging. If you can clear this consistently, you can walk…",
    "file": "DE-102_Mock_Test.html"
  },
  {
    "name": "DE-CORE | Python + SQL + PySpark + Airflow Focused Mock",
    "desc": "Python + SQL + PySpark + Airflow only. The four pillars every Data Engineering interview keeps circling back to — drilled at the tier of DE-101 /…",
    "file": "DE-CORE_Mock_Test.html"
  }
];
