#!/usr/bin/env node
/* ============================================================
   sync-content.js — regenerate content-config.js
   ------------------------------------------------------------
   Scans the library/ and tests/ folders, reads each HTML file's
   <title> and intro line, and writes content-config.js so every
   study guide and mock test shows up on EVERY device.

   Run it whenever you add (or remove) a file:

       node sync-content.js
       git add . && git commit -m "add new file" && git push

   No dependencies — plain Node.
   ============================================================ */

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const FOLDERS = [
  { dir: 'library', varName: 'LIBRARY_FILES' },
  { dir: 'tests', varName: 'TEST_FILES' },
];

function decodeEntities(s) {
  return String(s)
    .replace(/&mdash;/g, '—').replace(/&ndash;/g, '–').replace(/&bull;/g, '•')
    .replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&#39;/g, "'")
    .replace(/&[a-z]+;/gi, '').trim();
}

function firstMatch(html, regexes) {
  for (const re of regexes) {
    const m = re.exec(html);
    if (m && m[1] && m[1].trim()) return decodeEntities(m[1].replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' '));
  }
  return '';
}

function titleFor(html, file) {
  let t = firstMatch(html, [/<title>([\s\S]*?)<\/title>/i]);
  t = t.replace(/\s*[—-]\s*Deepesh\s*$/i, '').trim();      // drop personal suffix
  return t || path.basename(file, '.html').replace(/[_-]+/g, ' ');
}

function descFor(html) {
  const d = firstMatch(html, [
    /<p class="sub">([\s\S]*?)<\/p>/i,
    /<p class="tagline">([\s\S]*?)<\/p>/i,
    /<meta name="description" content="([^"]*)"/i,
  ]);
  if (!d) return '';
  return d.length > 155 ? d.slice(0, 152).replace(/\s+\S*$/, '') + '…' : d;
}

let out = `/* ============================================================
   content-config.js — AUTO-GENERATED by sync-content.js
   Do not edit by hand: your changes will be overwritten.

   To add a study guide or mock test:
     1. Put the .html file in  library/  or  tests/
     2. Run:  node sync-content.js
     3. git add . && git commit -m "add file" && git push

   Generated: ${new Date().toISOString().slice(0, 10)}
   ============================================================ */
`;

let counts = {};
for (const { dir, varName } of FOLDERS) {
  const abs = path.join(ROOT, dir);
  let entries = [];
  if (fs.existsSync(abs)) {
    entries = fs.readdirSync(abs)
      .filter(f => f.toLowerCase().endsWith('.html'))
      .sort()
      .map(f => {
        const html = fs.readFileSync(path.join(abs, f), 'utf8');
        return { name: titleFor(html, f), desc: descFor(html), file: f };
      });
  }
  counts[dir] = entries.length;
  out += `\nwindow.${varName} = ${JSON.stringify(entries, null, 2)};\n`;
}

fs.writeFileSync(path.join(ROOT, 'content-config.js'), out);
console.log(`content-config.js written — library: ${counts.library || 0} file(s), tests: ${counts.tests || 0} file(s)`);
for (const { dir } of FOLDERS) {
  const abs = path.join(ROOT, dir);
  if (!fs.existsSync(abs)) continue;
  fs.readdirSync(abs).filter(f => f.toLowerCase().endsWith('.html')).sort()
    .forEach(f => console.log(`  ${dir}/${f}`));
}
